version: '3.9'

services:
  nodetest:
    container_name: nodetest
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    restart: always